import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  'en-US': {
    Reward: 'Reward',
    // login
    welcomeBack: 'Welcome Back!',
    emailPlaceholder: 'Enter the email',
    passwordPlaceholder: 'Enter the password',
    login: 'Login',
    email: 'Email',
    password: 'Password',
    forgetPassword: 'Forget Password?',
    dontHaveAccnt: "Don't have an account? Sign Up",
    // sigup
    createAccount: 'Create Account',
    userId: 'User ID',
    fullName: 'Full Name',
    mobile: 'Mobile Number',
    position: 'Position',
    sponserID: "Sponser's ID",
    signupPassword: 'Password',
    confirmPassword: 'Confirm Password',
    signup: 'Sign Up',
    passwordNote:
      'Note: 1 capital letter, 1 small letter, 1 symbol, 1 number, min 8.',
    readPolicy: 'I read and agree to Terms and Condition',
    notRobot: "I'm not a robot",
    // forgot password
    forgotPassword: 'Forgot Password',
    userIdPlaceholder: 'Enter User ID',
    send: 'Send',
    submit: 'Submit',
    enterOtp: 'Enter OTP ',
    // Generate new pass
    generateNewPass: 'Generate New Password',
    generateNewPassParagraph: 'We recieved your reset password request. Please enter your new password',
    newPass: 'New Password',
    newPassPlaceholder: 'Enter new password',
    confirmNewPass: 'Confirm New Password',
    confirmNewPassPlaceholder: 'Confirm new password',
    updatePass: 'Update Password',
    passUpdateSuccessMessage: 'Your Password Has Been Updated!',
    gotoAccount: 'Go To Your Account',
    // thank you
    thankYouMessage: 'Thank You For Registration!',
    belowDetails: 'You have used your below details.',
    //sucess :
    Continue: 'Continue',
    UserAcc: ' User Account',
    Account: 'Account',
    AccountInfo: 'Account Information',
    UserId: 'User Id',
    FullName: 'Full name',
    sponserID: 'Sponsor ID',
    Country: 'Country',
    BTCAddress: ' BTC Address',
    Mobile: ' Mobile',
    InitiatePayment: 'Initiate Payment',
    Deposite: 'Deposit',
    EnterAmt: 'Enter Amount (In USD)',
    SelectMode: 'Select Mode',
    PreviewDeposite: 'Preview Deposite',
    savechanges: 'Save Changes',

    //unsett fund screen
    UnsettledFundReport: 'Unsettled Fund Report',
    fromdate: 'From Date',
    todate: 'To Date',
    DepositeId: 'Deposite Id',
    search: 'Search',
    reset: 'Reset',
    //SettledFund
    Search: 'Search',
    Deposit: 'Deposit ID',
    Submit: 'Submit',
    Show: 'Show',
    Entries: 'Entries',
    FromDate: 'From Date',
    ToDate: 'To Date',
    Confirm: 'Confirm',
    Cancel: 'Cancel',
    // Genealogy
    userIDPlaceholder: 'Enter User Id',
    createStructure: 'Create Structure',
    //SettledFund
    Search: 'Search',
    Deposit: 'Deposit ID',
    Submit: 'Submit',
    Show: 'Show',
    Entries: 'Entries',
    FromDate: 'From Date',
    ToDate: 'To Date',
    Confirm: 'Confirm',
    Cancel: 'Cancel',
    Reset:'Reset',
    // TeamView
    UserID: 'User Id',
    Prev: 'Prev',
    Next: 'Next',
  },
  IN: {
    Reward: 'इनाम',
  },
});
export default strings;
